import type { Report, ReportSection, ChartData } from '../types';

export class ReportGenerator {
  static generateEncryptionReport(
    plaintext: string,
    ciphertext: string,
    shift: number,
    method: string
  ): Report {
    const sections: ReportSection[] = [
      {
        title: 'Summary',
        content: `This report documents a ${method} operation performed on ${new Date().toLocaleString()}.`
      },
      {
        title: 'Input',
        content: `Plaintext: ${plaintext}\nShift: ${shift}\nMethod: ${method}`
      },
      {
        title: 'Output',
        content: `Ciphertext: ${ciphertext}`
      },
      {
        title: 'Security Notice',
        content: 'The Caesar cipher is a historical algorithm and should not be used for securing sensitive information. For real-world security, use modern cryptographic algorithms.'
      }
    ];

    return {
      id: crypto.randomUUID(),
      projectId: '',
      title: `${method} Report`,
      content: this.formatReport(sections),
      sections,
      generatedAt: new Date(),
      format: 'markdown'
    };
  }

  static generateAnalysisReport(
    text: string,
    frequencyData: Map<string, number>,
    recommendedShift: number
  ): Report {
    const sections: ReportSection[] = [
      {
        title: 'Analysis Summary',
        content: `Frequency analysis performed on ${new Date().toLocaleString()}. Recommended shift: ${recommendedShift}`
      },
      {
        title: 'Input Text',
        content: text.substring(0, 500) + (text.length > 500 ? '...' : '')
      },
      {
        title: 'Frequency Distribution',
        content: this.formatFrequencyData(frequencyData),
        charts: [this.createFrequencyChart(frequencyData)]
      },
      {
        title: 'Recommendation',
        content: `Based on the frequency analysis, the most likely shift value is ${recommendedShift}.`
      }
    ];

    return {
      id: crypto.randomUUID(),
      projectId: '',
      title: 'Frequency Analysis Report',
      content: this.formatReport(sections),
      sections,
      generatedAt: new Date(),
      format: 'markdown'
    };
  }

  static generateBruteForceReport(
    ciphertext: string,
    results: Array<{ shift: number; plaintext: string; score: number }>
  ): Report {
    const topResults = results.slice(0, 5);
    
    const sections: ReportSection[] = [
      {
        title: 'Brute Force Analysis',
        content: `Brute force analysis performed on ${new Date().toLocaleString()}.`
      },
      {
        title: 'Ciphertext',
        content: ciphertext
      },
      {
        title: 'Top Results',
        content: topResults
          .map((r, i) => `${i + 1}. Shift ${r.shift} (Score: ${r.score.toFixed(2)})\n   ${r.plaintext.substring(0, 100)}...`)
          .join('\n\n')
      },
      {
        title: 'Recommendation',
        content: `The most likely plaintext is with shift ${topResults[0]?.shift || 0}.`
      }
    ];

    return {
      id: crypto.randomUUID(),
      projectId: '',
      title: 'Brute Force Analysis Report',
      content: this.formatReport(sections),
      sections,
      generatedAt: new Date(),
      format: 'markdown'
    };
  }

  private static formatReport(sections: ReportSection[]): string {
    let report = '# CipherForge Pro Report\n\n';
    report += `Generated: ${new Date().toLocaleString()}\n\n`;
    report += '---\n\n';

    for (const section of sections) {
      report += `## ${section.title}\n\n`;
      report += `${section.content}\n\n`;
    }

    report += '---\n\n';
    report += '*This report was generated by CipherForge Pro - Educational Cryptography Toolkit*\n';
    report += '*The Caesar cipher is not secure for real-world use.*\n';

    return report;
  }

  private static formatFrequencyData(data: Map<string, number>): string {
    let output = 'Letter | Frequency\n';
    output += '-------|----------\n';
    
    const sorted = Array.from(data.entries()).sort((a, b) => b[1] - a[1]);
    for (const [letter, freq] of sorted) {
      output += `${letter.padEnd(7)}| ${(freq * 100).toFixed(2)}%\n`;
    }
    
    return output;
  }

  private static createFrequencyChart(data: Map<string, number>): ChartData {
    const entries = Array.from(data.entries()).sort((a, b) => b[1] - a[1]);
    
    return {
      type: 'bar',
      labels: entries.map(([letter]) => letter),
      datasets: [{
        label: 'Frequency',
        data: entries.map(([, freq]) => freq * 100),
        backgroundColor: 'rgba(99, 102, 241, 0.5)',
        borderColor: 'rgba(99, 102, 241, 1)'
      }]
    };
  }

  static exportAsMarkdown(report: Report): string {
    return report.content;
  }

  static exportAsJSON(report: Report): string {
    return JSON.stringify(report, null, 2);
  }

  static exportAsHTML(report: Report): string {
    let html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${report.title}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; line-height: 1.6; color: #333; }
    h1 { color: #6366f1; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
    h2 { color: #4f46e5; margin-top: 30px; }
    pre { background: #f1f5f9; padding: 15px; border-radius: 8px; overflow-x: auto; }
    .disclaimer { background: #fef3c7; border: 1px solid #f59e0b; padding: 15px; border-radius: 8px; margin-top: 30px; }
    .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 0.875rem; }
  </style>
</head>
<body>
  <h1>${report.title}</h1>
  <p><em>Generated: ${report.generatedAt.toLocaleString()}</em></p>
`;

    for (const section of report.sections) {
      html += `  <h2>${section.title}</h2>\n`;
      html += `  <pre>${section.content}</pre>\n`;
    }

    html += `
  <div class="disclaimer">
    <strong>Educational Disclaimer:</strong> The Caesar cipher is not secure for real-world use. 
    For secure encryption, use modern algorithms like AES-256, RSA, or ChaCha20.
  </div>
  
  <div class="footer">
    <p>Generated by CipherForge Pro - Educational Cryptography Toolkit</p>
  </div>
</body>
</html>`;

    return html;
  }
}

export const reportGenerator = new ReportGenerator();
